version: '3.9'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app  # Оставляем монтирование для удобства разработки
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=App.settings

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
