# Generated by Django 5.0.7 on 2024-08-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.URLField(),
        ),
    ]
