# Generated by Django 5.0.7 on 2024-08-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0002_alter_post_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
